const Card_BG = [
  {id: 1, bgcolor: 'linear-gradient(135deg, #e6f8f3 0%, #7f7cfa 100%)'},
{id: 2, bgcolor: 'linear-gradient(135deg, #efe7f7 0%, #3f1b81 100%)'},
{id: 3, bgcolor: 'linear-gradient(135deg, #eae7f7 0%, #3f1b81 100%)'},
{id: 4, bgcolor: 'linear-gradient(135deg, #fff7e9 0%, #1f813 100%)'},
{id: 5, bgcolor: 'linear-gradient(135deg, #e7f6f0 0%, #f4f1d 100%)'},
{id: 6, bgcolor: 'linear-gradient(135deg, #f5f5f5 0%, #bfbfbf 100%)'},
{id: 7, bgcolor: 'linear-gradient(135deg, #fff4fc 0%, #f8f8f8 100%)'},
{id: 8, bgcolor: 'linear-gradient(135deg, #e8e3f3 0%, #f5f8f8 100%)'},
{id: 9, bgcolor: 'linear-gradient(135deg, #0fecff 0%, #f7f5f1 100%)'},
{id: 10, bgcolor: 'linear-gradient(135deg, #fef2f2 0%, #fff8f8 100%)'},
];
export default Card_BG;        


export const APP_FEATURES = [
  {
    id: "01",
    title: "Tailored Just for You",
    description:
      "Get interview questions and model answers based on your role, experience, and specific focus areas – no fluff.",
  },
  {
    id: "02",
    title: "Learn at Your Own Pace",
    description:
      "Expand answers only when you're ready. Dive deeper into any concept instantly with AI-powered detailed explanations.",
  },
  {
    id: "03",
    title: "Capture Your Insights",
    description:
      "Add personal notes to any question and pin important ones to the top – making your learning more organized.",
  },
  {
    id: "04",
    title: "Understand the 'Why' Behind Answers",
    description:
      "Beyond just answers – unlock detailed concept explanations generated by AI, helping you truly master each topic.",
  },
  {
    id: "05",
    title: "Save, Organize and Revisit",
    description:
      "Easily save your interview sets , organise them nearly in your dashboard, and pick up your preparetion right where you left off",
  },
];